#!/bin/sh

MODE=$1
FKEY=$2
FOCUSEDOUTPUT=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).output' | cut -d"\"" -f2)


if [ "$FOCUSEDOUTPUT" = "DP-2" ]
	then
	WORKSPACE=$((FKEY + 20))
elif [ "$FOCUSEDOUTPUT" = "DP-4" ]
	then
	WORKSPACE=$((FKEY + 30))
else
	WORKSPACE=$((FKEY))
fi


if [ "$MODE" = "focus" ]
	then
	i3-msg "workspace ${WORKSPACE}"
elif [ "$MODE" = "move" ]
	then
	i3-msg "move container to workspace ${WORKSPACE}"
fi