code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Equinusocio.vsc-material-theme
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension PKief.material-icon-theme
code --install-extension alefragnani.Bookmarks
code --install-extension alexdima.copy-relative-path
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension hollowtree.vue-snippets
code --install-extension ionutvmi.spacegray-vscode
code --install-extension liuji-jim.vue
code --install-extension octref.vetur
code --install-extension sdras.vue-vscode-extensionpack
code --install-extension sdras.vue-vscode-snippets
code --install-extension teabyii.ayu
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomphilbin.gruvbox-themes
code --install-extension vscodevim.vim
code --install-extension whizkydee.material-palenight-theme
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.JavaScriptSnippets
